- name: config backend
  hosts: backend
  become: yes
  tasks:

  - name: disable current node js
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enable node js20
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: install nodejs
    ansible.builtin.package:
      name: nodejs
      state: present