- name: config backend
  hosts: backend
  become: yes
  tasks:

  - name: disable current node js
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enable node js20
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: install nodejs
    ansible.builtin.package:
      name: nodejs
      state: present

  - name: add user
    ansible.builtin.user:
      name: expense

  - name: create app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: download the file
    ansible.builtin.get_url:
      url: https://github.com/KattaHarshavardhanReddy/Ansible1.git
      dest: /tmp/backend.zip

  - name: unzip the file
    ansible.builtin.unarchive:
      src: /tmp/backend.zip
      dest: /app
      remote_src: yes